language: android
#jdk: oraclejdk8
#build with travis
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew

script:
  ./gradlew build
